### PR TITLE
Upgrade s6-overlay from 2.2.0.3 to 3.1.0.1

### PR DESCRIPTION
**Pull request by felipecrs**
## Breaking Changes

The latest version contains lots of breaking changes. So far, these are the ones I counted:

- `S6_CMD_WAIT_FOR_SERVICES_MAXTIME` now is considered even when `CMD` is unset (which is the case for every addon which had implemented s6-overlay services correctly).
   -  I worked around with https://github.com/hassio-addons/addon-base/pull/176/commits/3ccc150f942d566f914a8d580df1132776ebd9d8, therefore it should not cause any issue for addon developers.
- Execution permission must be added for every single script meant to be executed by s6. Previously, s6-overlay would fix the permissions on the fly. Therefore, for the addon developers, they need to do:
    
    ```console
    $ chmod +x <addon>/rootfs/etc/cont-init.d/*.sh
    $ chmod +x <addon>/rootfs/etc/services.d/<service>/*
    $ git add .
    $ git commit -m "Add execution permission for s6 scripts"
    ```
    
    Or, if you are on Windows, change `chmod +x <files>` to `git add --chmod=+x <files>`.
- ~Default `PATH` changes.~ [Not needed anymore since 3.1.0.0](https://github.com/hassio-addons/addon-base/pull/176/commits/d532a3d51cb38816aa05e53df9730ce296ded4ce)
  
  It defaults to `/comand:/usr/bin:/bin`, which is radically different than before. The https://github.com/hassio-addons/addon-base/pull/176/commits/8351d078c88f49300f72289bef391ea676e3a763 alleviates this change by making the S6 default PATH equals to what it was before (which can be refactored to `S6_GLOBAL_PATH` once 3.1.0.0 gets released), but if in your `Dockerfile` you are extending the `PATH` environment variable with custom directories, you need to add the following in your `Dockerfile`:
    
    ```dockerfile
    # Before
    ENV PATH="/my/custom/directory:${PATH}"
    ```
    
    ```dockerfile
    # After
    ENV PATH="/my/custom/directory:${PATH}"
    RUN echo "${PATH}" | tee /etc/s6-overlay/config/global_path
    ```
    
    Of course, this can be improved, like by adding the `/etc/s6-overlay/config/global_path` to your `rootfs` folder if you know the value of it in beforehand.
    
    But I will prefer to use something like https://github.com/just-containers/s6-overlay/issues/417 if it gets accepted/implemented.

- `S6_STAGE2_EXITED` is not set anymore. Workaround is to rely on the contents of `/run/s6-linux-init-container-results/exitcode` instead. See https://github.com/hassio-addons/addon-base/pull/176/commits/aabdf7919108a2cf74adab5e14e71bc8ae360fdc for an example.
    - Caveat: `/etc/cont-finish.d/*.sh` are called anymore when `/etc/cont-init.d/*.sh` fails. See https://github.com/just-containers/s6-overlay/issues/406#issuecomment-1034986802.

- Some s6 binaries have changed locations. But this hopefully won't be a problem. See: https://github.com/just-containers/s6-overlay/issues/404#issuecomment-1034322406

This list is not finished. I will add more once I find.

## References

- https://github.com/just-containers/s6-overlay#installation
- This fixes https://github.com/hassio-addons/addon-base-python/issues/102, even though it can be fixed by https://github.com/hassio-addons/addon-base-python/pull/103 as well.

## TODOs

- [ ] Refactor cont-init and cont-finish scripts into new format. See: https://github.com/just-containers/s6-overlay/issues/406#issuecomment-1035686398

### CODE REVIEW

**Comment by sinclairpaul** [comment]
Would be great to detail some of the testing you have done on this, it's quite a major impact.

**Comment by felipecrs** [comment]
I pushed `ghcr.io/felipecrs/addon-base/amd64:pr-176`. Now I'm going to make a known addon use it and see if things still works.

**Comment by felipecrs** [comment]
Indeed. This is going to be a big one. I collected some breaking changes to be aware of, so far:

- `S6_CMD_WAIT_FOR_SERVICES_MAXTIME` now is considered even when `CMD` is unset (which is the case for EVERY addon). I worked around with https://github.com/hassio-addons/addon-base/pull/176/commits/3ccc150f942d566f914a8d580df1132776ebd9d8, therefore it should not cause any issue for addon developers.
- Execution permission must be added for every single script meant to be executed by S6. Previously, S6 Overlay would fix the permissions on the fly. Therefore, for the addon developers, they need to do:
    
    ```console
    $ chmod +x <addon>/rootfs/etc/cont-init.d/*.sh
    $ chmod +x <addon>/rootfs/etc/services.d/<service>/*
    $ git add .
    $ git commit -m "Add execution permission for s6 scripts"
    ```
    
    Or, if you are on Windows, change `chmod +x <files>` to `git add --chmod=+x <files>`.
    
This list is not finished.

**Comment by crazy-max** [comment]
@felipecrs See also https://github.com/crazy-max/docker-alpine-s6/blob/00fe18989aabd61021671db6d0aafff3af0b6236/Dockerfile#L220. Maybe my base image could work for you for this image: https://github.com/crazy-max/docker-alpine-s6#usage

**Comment by felipecrs** [comment]
@crazy-max this is **really** nice. We definitely need to take a look on it. It seems to contain some things other than we had before, like `syslogd` but it may actually turn out to be a good thing to have indeed. A little bit of investigation will be required from my side.

I wish I could install it using the `dist` image variant with the `COPY --from`, but for some reason (unknown to me), Home Assistant image builder does not play nice with the way Docker handles multi-archictecture images. But I can of course download the archives from your Releases.

Thank you for pointing this out!

**Comment by felipecrs** [comment]
Done, I would say that the only missing thing is the refactor on the `cont-init.d` and `cont-finish.d` scripts to the new format.

**Comment by frenck** [comment]
@felipecrs What refactoring are you referring to?

**Comment by mdegat01** [comment]
The other one from [the blog post](https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images) that's not discussed in here is the requirement to have `init: false` in the config of every addon. In V3 S6 now checks that it is in fact PID 1 on startup or it simply refuses to start. This is different from V2 where it didn't like that but would allow it.

The blog post doesn't mention this one and I don't remember seeing issues around this in testing:
> S6_STAGE2_EXITED is not set anymore. Workaround is to rely on the contents of /run/s6-linux-init-container-results/exitcode instead. See https://github.com/hassio-addons/addon-base/commit/aabdf7919108a2cf74adab5e14e71bc8ae360fdc for an example.

Is it specifically for `cont-finish.d` scripts? Because the exit code is still being passed in to `finish` scripts in `services.d`, this worked fine for example:
https://github.com/home-assistant/supervisor/blob/2c09021427416b84e4f1ad5a12d918fb5e95f9c5/rootfs/etc/services.d/supervisor/finish

Possibly something else to add @pvizeli ?

**Comment by frenck** [comment]
> FYI I think this update to s6 v3 would break the [glances add-on](https://github.com/hassio-addons/addon-glances) because it uses the host_pid option.

S6 was actually never suited for running that way, the fact it currently works with glances, is a hack to begin with.

**Comment by frenck** [comment]
Looking at the task/issue left, I'm not sure if we should re-write everything to use the `s6-rc` oneshots. While that is probably recommended right now (documentation is vague about it, just that `cont-init.d` and `cont-finish.d` are called legacy in a couple of places); I think the current structure is simpler compared to the oneshot services.

The simplicity kind of wins here for me. Especially considering the dependencies we need to make (downstream in add-ons) to keep everything nice and tidy.

So, essentially, that means `cont-finish.d/99-message.sh` can either:

- Left alone. Sometimes it works, sometimes it doesn't.
- Removed. It is not mission-critical.

Currently, my guts say: Go for the latter. Remove it for consistency.

What you do think @felipecrs?

**Comment by felipecrs** [comment]
Speaking specifically about the `99-message.sh`, I believe it would not be too complicated to refactor it into the new format.

But everything else you said is valid, especially considering downstream.

**Comment by felipecrs** [comment]
> Speaking specifically about the 99-message.sh, I believe it would not be too complicated to refactor it into the new format.

I can do it. Should I?

**Comment by felipecrs** [comment]
Anyway, the documentation of s6-overlay says:

> We encourage you to switch to the new format, but if you don't need its benefits, you can stick with regular service directories in /etc/services.d, it will work just as well.

Which means that it's not deprecated. So, I would agree with you on:

- Removed. It is not mission-critical.

If we decide not to encorage downstream to refactor their services as well.

**Comment by frenck** [comment]
> I can do it. Should I?

How would you handle service dependencies?

> If we decide not to encourage downstream to refactor their services as well.

That can be decided downstream, anyone is free to do so 🤷

**Comment by felipecrs** [comment]
> How would you handle service dependencies?

Meaning how would I ensure that everything runs in the right order? You are right.

We may better remove the message entirely then.

**Comment by frenck** [comment]
Alright, lets do that 👍

**Review by frenck — APPROVED** [review]
This looks good to start/go to me. As I'm aiming to release a major version of the base image (with Alpine 3.16), I'm merging this one for testing.

We can always build & extend on this if needed.

**Comment by frenck** [comment]
Thanks, @felipecrs 🎉

**Pull request merged**
